<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Галерея");
?> <?$APPLICATION->IncludeComponent("bitrix:photogallery.section.list", "gardis_galery_list", array(
	"IBLOCK_TYPE" => "information",
	"IBLOCK_ID" => "19",
	"SECTION_ID" => $_REQUEST["SECTION_ID"],
	"SECTION_CODE" => "",
	"BEHAVIOUR" => "SIMPLE",
	"PHOTO_LIST_MODE" => "N",
	"SORT_BY" => "UF_DATE",
	"SORT_ORD" => "ASC",
	"PAGE_ELEMENTS" => "9",
	"INDEX_URL" => "",
	"SECTION_URL" => "/gallery/#SECTION_ID#/",
	"SECTION_EDIT_URL" => "section_edit.php?SECTION_ID=#SECTION_ID#",
	"SECTION_EDIT_ICON_URL" => "section_edit_icon.php?SECTION_ID=#SECTION_ID#",
	"UPLOAD_URL" => "upload.php?SECTION_ID=#SECTION_ID#",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"ALBUM_PHOTO_SIZE" => "173",
	"ALBUM_PHOTO_THUMBS_SIZE" => "173",
	"PAGE_NAVIGATION_TEMPLATE" => "gardis_navigation",
	"DATE_TIME_FORMAT" => "d.m.Y",
	"SET_STATUS_404" => "N",
	"SET_TITLE" => "N"
	),
	false
);?>
<br />
<?/*$APPLICATION->IncludeComponent("bitrix:news.list", "gardis_news_list_mini", array(
	"IBLOCK_TYPE" => "information",
	"IBLOCK_ID" => "15",
	"NEWS_COUNT" => "3",
	"SORT_BY1" => "ACTIVE_FROM",
	"SORT_ORDER1" => "DESC",
	"SORT_BY2" => "SORT",
	"SORT_ORDER2" => "ASC",
	"FILTER_NAME" => "",
	"FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"CHECK_DATES" => "Y",
	"DETAIL_URL" => "",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"PREVIEW_TRUNCATE_LEN" => "",
	"ACTIVE_DATE_FORMAT" => "j F Y",
	"SET_TITLE" => "N",
	"SET_STATUS_404" => "N",
	"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
	"ADD_SECTIONS_CHAIN" => "N",
	"HIDE_LINK_WHEN_NO_DETAIL" => "N",
	"PARENT_SECTION" => "",
	"PARENT_SECTION_CODE" => "",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "N",
	"PAGER_TITLE" => "Новости",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_TEMPLATE" => "",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "N",
	"DISPLAY_DATE" => "Y",
	"DISPLAY_NAME" => "Y",
	"NO_VOTE" => "Y",
	"DISPLAY_PREVIEW_TEXT" => "Y",
	"HREF" => "/about/news/",
	"AJAX_OPTION_ADDITIONAL" => ""
	),
	false
);*/?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>